services:
 rustapp:
  container_name: rustapp
  image: image-name:latest
  build:
   context: ./backend
   dockerfile: rust.dockerfile
   args:
    DATABASE_URL: add-url

 db:
  container_name: db 
  image: postgres:13
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: postgres
  ports: 
   - 5432:5432
  volumes:
   - pgdata:/var/lib/postgresql/data 
 

volumes:
 gdata: {}

 